TheTalkSquare/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^user', include('login.urls')),
    url(r'^admin/', admin.site.urls),
]

login/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

app_name = 'login' 
#This sets application namespace to diffretiate urls of different apps.

urlpatterns = [
    #url for login-page:
    url(r'/login$', views.login, name='login'),

    #url for signup-page:
    url(r'/signup$', views.signup, name='signup'),

    #url to log in a user:
    url(r'/log_req$', views.logInReq, name='login_req'),
    
    #url for create-user:
    url(r'/register_user$', views.register, name='register_user'),

    #url for logout:
    url(r'/logout$', views.logout, name='logout'),
]

main/urls.py
from django.conf.urls import url

from . import views


app_name = 'main' 
#This sets application namespace to diffretiate urls of different apps.

urlpatterns = [
    #url for home-page:
    url(r'^$', views.index, name='index'),

    #url to Enter a new Topic:
    url(r'^add_topic$', views.addtopic, name='addtopic'),

    #url to Enter a new Topic:
    url(r'^add_opinion$', views.addopinion, name='addopinion'),

    #url to topic page:
    url(r'^(?P<pk>[0-9]+)/topic$', views.TopicView.as_view(), name='topic'),

    #url to search a topic:
    url(r'^search$', views.search, name='search'),
]

login/models.py
from django.db import models

class User(models.Model):
    user_name = models.CharField(max_length=80,unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=120)
    pwd= models.CharField(max_length=80)
    #no_of_topics=models.IntegerField(default=0)
    #type_user=models.BooleanField()
    def __str__(self):
        return self.user_name

main/models.py
from django.db import models
from login.models import User

class Topic(models.Model):
    #tags = models.ForeignKey(Tag, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    topic_text = models.CharField(max_length=250)
    topic_desc=models.CharField(max_length=700,default="")
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.topic_text


class Tag(models.Model):
    tag_name= models.CharField(max_length=50)
    tag_desc=models.CharField(max_length=500,default="")
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
    def __str__(self):
        return self.tag_name

class Opinion(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    opinion_text=models.CharField(max_length=500)
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)
    foragainst=models.IntegerField(default=0) #for=1 against=0
    def __str__(self):
        return self.user.user_name

login/forms.py
from django import forms

class SignupForm(forms.Form):
    username=forms.CharField(max_length = 80)
    firstname = forms.CharField(max_length=30)
    lastname = forms.CharField(max_length=30)
    email = forms.CharField(max_length=120)
    pwd= forms.CharField(max_length=80)

class LoginForm(forms.Form):
    username=forms.CharField(max_length = 80)
    pwd= forms.CharField(max_length=80)

main/forms.py
from django import forms

class LoginForm(forms.Form):
    username=forms.CharField(max_length = 80)
    pwd= forms.CharField(max_length=80)

class AddTopicForm(forms.Form):
    topic_text=forms.CharField(max_length = 250)
    topic_desc=forms.CharField(max_length = 700)
    tag_text=forms.CharField(max_length = 250)

class AddOpinionForm(forms.Form):
    opinion_text=forms.CharField(max_length = 500)
    topic = forms.CharField(max_length = 5)

class SearchForm(forms.Form):
    topic_text=forms.CharField(max_length = 250)

login/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect

from django.urls import reverse
#for older versoins of Django use:
#from django.core.urlresolvers import reverse

from .models import User
from .forms import SignupForm,LoginForm

def login(request):
    return render(request, 'Html/login.html')
def signup(request):
    return render(request, 'Html/signup.html')

def register(request):
    if request.method == 'POST':
        signup=SignupForm(request.POST)
        if signup.is_valid():
            p=User(user_name=signup.cleaned_data.get('username'),first_name=signup.cleaned_data.get('firstname'),last_name=signup.cleaned_data.get('lastname'),email=signup.cleaned_data.get('email'),pwd=signup.cleaned_data.get('pwd'))
            p.save()
    request.session['user_id'] = p.id
    return HttpResponseRedirect(reverse('main:index'))

def logInReq(request):
    if request.method == 'POST':
        log=LoginForm(request.POST)
        if log.is_valid():
            try:
                user=User.objects.get(user_name=log.cleaned_data.get('username'),pwd=log.cleaned_data.get('pwd'))
                request.session['user_id'] = user.id
                return HttpResponseRedirect(reverse('main:index'))
            except User.DoesNotExist:
                return HttpResponse("WRONG USERNAME OR PASSWORD")

def logout(request):
   try:
      del request.session['user_id']
   except:
      pass
   return HttpResponseRedirect(reverse('main:index'))

main/views.py
from django.shortcuts import render,get_object_or_404
from django.core.exceptions import ObjectDoesNotExist #This may be used instead of Users.DoesNotExist
from django.http import HttpResponse,HttpResponseRedirect
from django.views import generic
import re

from django.urls import reverse
#for older versoins of Django use:
#from django.core.urlresolvers import reverse


from .models import Topic,Opinion,Tag
from login.models import User
from main.forms import LoginForm,AddTopicForm,AddOpinionForm,SearchForm

def index(request):
    if request.session.has_key('user_id'):
        uid=request.session['user_id']
        try:
            li=Topic.objects.order_by('-pk')[:10]
            user=User.objects.get(pk=uid)
            return render(request, 'Temp/logged.html',{'user_id':user,"list":li})
        except User.DoesNotExist:
            return HttpResponse("UserName not found")
    else:
        return render(request, 'Temp/main.html')


def search(request):
    if request.method == 'POST':
        topic=SearchForm(request.POST)
        if topic.is_valid():

            #t=Topic.objects.get(topic_text=topic.cleaned_data.get('topic_text'))
            top_li = Topic.objects.all()
            li=[]
            for t in top_li:
                if re.search(topic.cleaned_data.get('topic_text'),t.topic_text,re.IGNORECASE):
                    li.append(t)
            if request.session.has_key('user_id'):
                uid = request.session['user_id']
                user = User.objects.get(pk=uid)
                return render(request, 'Temp/searchresults.html', {'user_id':user,"list": li})
            else:
                return render(request, 'Temp/searchresults.html', {"list": li})
        else:
            return HttpResponse("Form not valid")
    else:
        return HttpResponse("not POST")



"""
class LoggedIn(generic.DetailView):
	model = Users
	template_name = 'Temp/logged.html'
	context_object_name = 'user_id'
"""


def addtopic(request):
    if request.method == 'POST':
        uid = request.session['user_id']
        topic=AddTopicForm(request.POST)
        if topic.is_valid():
            tag = []
            tag_str=topic.cleaned_data.get('tag_text')
            topic_str = topic.cleaned_data.get('topic_text')
            topic_desc = topic.cleaned_data.get('topic_desc')
            tag = tag_str.split(',')
            p=Topic(user=User.objects.get(pk=uid),topic_text=topic_str,topic_desc=topic_desc)
            p.save()
            try:
                for i in tag:
                    q = Tag(topic=Topic.objects.get(topic_text=topic_str),
                            tag_name=i)
                    q.save()
            except:
                return HttpResponse("Topic already exists")
        else:
            return HttpResponse("Form not valid")
    else:
        return HttpResponse("not POST")
    return HttpResponseRedirect(reverse('main:index'))

def addopinion(request):
    if request.method == 'POST':
        uid = request.session['user_id']
        opinion=AddOpinionForm(request.POST)
        if opinion.is_valid():
            top=Topic.objects.get(pk=opinion.cleaned_data.get('topic'))
            p=Opinion(user=Users.objects.get(pk=uid),opinion_text=opinion.cleaned_data.get('opinion_text'),topic=top)
            p.save()
        else:
            return HttpResponse("Form not valid")
    else:
        return HttpResponse("not POST")
    return HttpResponseRedirect(reverse('main:topic', args=(opinion.cleaned_data.get('topic'))))

class TopicView(generic.DetailView):
	model = Topic
	template_name = 'Temp/Topic.html'

	context_object_name = 't'

main/templates/Temp/Topic.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>

    <meta charset="utf-8">
    <title>TheTalkSquare</title>
    <meta name="generator" content="Bootply"/>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/stylish-portfolio.css' %}" rel="stylesheet">
    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "70%";
            // document.getElementById("flipkart-navbar").style.width = "50%";
            document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.body.style.backgroundColor = "rgba(0,0,0,0)";
        }
    </script>

</head>
<body>
<body>


<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<div id="flipkart-navbar" style="background: #576396">
    <div class="container">
        <div class="row row1" style="margin-top: 20px;padding-bottom:20px">
            <div class="col-sm-2">
                <h2 style="margin:0px;"><span class="smallnav menu" onclick="openNav()">☰ OPINIUM</span></h2>
                <h1 style="margin:0px;"><span class="largenav">OPINIUM</span></h1>
            </div>
            <div class="flipkart-navbar-search smallsearch col-sm-8">
                <div class="row">

                    <form class="form" method="POST" action="{% url 'main:search' %}"><!--Not applied yet -->
                        {% csrf_token %}
                        <input style="color:#000" class="flipkart-navbar-input col-xs-11" name="topic_text" type=""
                               placeholder="Search for Issues and more" required>
                        <button class="flipkart-navbar-button col-xs-1">
                            <svg width="15px" height="15px">
                                <path d="M11.618 9.897l4.224 4.212c.092.09.1.23.02.312l-1.464 1.46c-.08.08-.222.072-.314-.02L9.868 11.66M6.486 10.9c-2.42 0-4.38-1.955-4.38-4.367 0-2.413 1.96-4.37 4.38-4.37s4.38 1.957 4.38 4.37c0 2.412-1.96 4.368-4.38 4.368m0-10.834C2.904.066 0 2.96 0 6.533 0 10.105 2.904 13 6.486 13s6.487-2.895 6.487-6.467c0-3.572-2.905-6.467-6.487-6.467 "></path>
                            </svg>
                        </button>
                    </form>
                </div>
            </div>
            <div class="col-sm-1">
                <ul style="padding-top:5px;list-style:none">
                    {% if request.session.user_id %}
                    <li><h4 style="font-size: 15px;font-weight: bolder"> {{ user_id.user_name }}</h4> </li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-sm-1">
                <ul style="padding-top:5px;list-style:none">
                    {% if request.session.user_id %}
                    <li><a style="font-size: 15px;font-weight: bolder" href="{% url 'login:logout' %}" class="btn btn-warning">Log Out</a></li>
                    {% else %}
                    <li><a style="font-size: 15px;font-weight: bolder" href="{% url 'login:login' %}" class="btn btn-warning">Log In</a></li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </div>
</div>
<br>
<div class="container"  style="background: #eeeeee">
    <div class="container" >
        <h2><b>{{ t.topic_text }}</b></h2>
        <h5><b>{{ t.user.user_name }}</b></h5>
        {% if t.tag_set.all %}
            {% for i in t.tag_set.all %}
                <a href=""><span
                        class="badge badge-info">

                {{ i.tag_name }}
                </span>
                </a>
            {% endfor %}
        {% else %}
            No Tags
        {% endif %}
<div><br></div>

            <div  style="width: 1100px;font-size: 16px;font-weight: bold">

                {{ t.topic_desc }}
        </div>

    </div>

    <ul style="list-style-type: none;padding: 40px 10px ;border-bottom: 3px solid white">
        {% if t.opinion_set.all %}
            {% for i in t.opinion_set.all %}
                <li style="background: #fff;padding: 10px;border-radius:5px;margin-bottom: 10px"><b>{{ i.opinion_text }}</b><i><br>By:{{ i.user.user_name }}</i></li>
            {% endfor %}
        {% else %}
            <li>No opinions on this topic yet.
        {% endif %}
    </ul>

 {% if request.session.user_id %}
<h4>Comment Sectoion : </h4>
    <div class="modal-body">
        <form class="form" method="POST" action="{% url 'main:addopinion' %}">
            {% csrf_token %}

            <div class="row">
                <div class="form-group col-sm-10">
                    <textarea type="text"  name="opinion_text" rows="5"  class="form-control"
                           placeholder="Give your valuable opinion here:" required >
                        </textarea>
                </div>

                <div class="form-group col-sm-2">
                    <button class="btn btn-success">Add opinion</button>
                </div>
                <input name="topic" value="{{ t.id }}" style="visibility: hidden">
            </div>
        </form>
    </div>
</div>
{% else %}
<h4>Log-In to give your opinion: <a style="font-size: 15px;font-weight: bolder" href="{% url 'login:login' %}" class="btn btn-warning">Log In</a></h4>
{% endif %}

<script type="text/javascript"
        src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5892d5e98848c5c0"></script>
</body>
</html>

main/templates/Temp/logged.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>

    <meta charset="utf-8">
    <title>TheTalkSquare</title>
    <meta name="generator" content="Bootply"/>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/stylish-portfolio.css' %}" rel="stylesheet">
    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "70%";
            // document.getElementById("flipkart-navbar").style.width = "50%";
            document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.body.style.backgroundColor = "rgba(0,0,0,0)";
        }
    </script>
</head>
<body style="background: #eeeeee">


<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<div id="flipkart-navbar" style="background: #576396">
    <div class="container">
        <div class="row row1" style="margin-top: 20px;padding-bottom:20px">
            <div class="col-sm-2">
                <h2 style="margin:0px;"><span class="smallnav menu" onclick="openNav()">☰ OPINIUM</span></h2>
                <h1 style="margin:0px;"><span class="largenav">OPINIUM</span></h1>
            </div>
            <div class="flipkart-navbar-search smallsearch col-sm-8">
                <div class="row">

                    <form class="form" method="POST" action="{% url 'main:search' %}"><!--Not applied yet -->
                        {% csrf_token %}
                        <input style="color:#000" class="flipkart-navbar-input col-xs-11" name="topic_text" type=""
                               placeholder="Search for Issues and more" required>
                        <button class="flipkart-navbar-button col-xs-1">
                            <svg width="15px" height="15px">
                                <path d="M11.618 9.897l4.224 4.212c.092.09.1.23.02.312l-1.464 1.46c-.08.08-.222.072-.314-.02L9.868 11.66M6.486 10.9c-2.42 0-4.38-1.955-4.38-4.367 0-2.413 1.96-4.37 4.38-4.37s4.38 1.957 4.38 4.37c0 2.412-1.96 4.368-4.38 4.368m0-10.834C2.904.066 0 2.96 0 6.533 0 10.105 2.904 13 6.486 13s6.487-2.895 6.487-6.467c0-3.572-2.905-6.467-6.487-6.467 "></path>
                            </svg>
                        </button>
                    </form>
                </div>
            </div>
            <div class="col-sm-1">
                <ul style="padding-top:5px;list-style:none">
                    <li><h4 style="font-size: 15px;font-weight: bolder"> {{ user_id.user_name }}</h4>


                    </li>
                </ul>
            </div>
            <div class="col-sm-1">
                <ul style="padding-top:5px;list-style:none">
                    <li><a style="font-size: 15px;font-weight: bolder" href="{% url 'login:logout' %}" class="btn btn-warning">Log Out</a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid" style="margin-top: 20px">
    <div class="row">
        <div class="col-sm-9">
            <ul style="list-style-type: none" >
                {% if list %}
                    {% for i in list %}
                        <div style="border:1px solid #eeeeee;background:#fff;margin-bottom: 5px;border-radius:5px;padding:0px 20px 10px 20px">
                            <h3><a
                                    href="{% url 'main:topic' i.id %}">{{ i.topic_text }}</a>
                            </h3>

                            <p class="lead" style="font-size:15px"> >&nbsp;{{ i.user.user_name }}
                            </p>
                                {% if i.tag_set.all %}
                                        Tags:                            
                                {% for j in i.tag_set.all %}
                                            <a href=""><span
                                class="badge badge-info">                                
                                {{ j.tag_name }}
        </span></a>
                            {% endfor %}
                        {% else %}
                           
                        {% endif %}

                        </div>
                    {% endfor %}
                {% else %}
                    <li>No topics available</li>
                {% endif %}
            </ul>
        </div>

        <div class="col-sm-3" style="position: fixed;right:0;border: 1px solid #e3e3e3;padding: 10px;background: #576396;border-radius: 5px">
            <form class="form" method="POST" action="{% url 'main:addtopic' %}">
                {% csrf_token %}
                <input type="text" class="form-control input-lg" name="topic_text"
                       placeholder="Enter a new topic:" required>
                   <br>
             <input type="text" class="form-control input-lg" name="topic_desc" placeholder="Enter topic description:" required>
<br>
                <input type="text" class="form-control input-lg" name="tag_text" placeholder="Enter tags:"
                       required>
                <br>
                <button class="btn btn-default">Add Topic</button>

            </form>
        </div>
    </div>
</div>
<script type="text/javascript"
        src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5892d5e98848c5c0"></script>
</body>
</html>

main/templates/Temp/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>TheTalkSquare</title>
		<meta name="generator" content="Bootply" />
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="{% static 'css/styles.css' %}" rel="stylesheet">
		
		 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/stylish-portfolio.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic' %}" rel="stylesheet" type="text/css">
	
	</head>
	<body>
<!--login modal-->
<header id="top" class="header">
        <div class="text-vertical-center">
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <h1 class="text-center">Login</h1>
      </div>


      <div class="modal-body">
          <form class="form col-md-12 center-block" method="POST" action="{% url 'main:login_req' %}">
			{% csrf_token %} 
            <div class="form-group">
              <input type="text" class="form-control input-lg" name="username" placeholder="UserName" required>
            </div>
            <div class="form-group">
              <input type="password" class="form-control input-lg" name="pwd" placeholder="Password" required>
            </div>
            <div class="form-group">
              <button class="btn btn-primary btn-lg btn-block">Sign In</button>
              <!--<span class="pull-right"><a href="signup.html">Register</a></span>
			  <span><a href="#">Need help?</a></span>-->
            </div>
          </form>
      </div>


      <div class="modal-footer">
      </div>
  </div>
  </div>
</div>
	
</div>
</header>
</body>
</html>

main/templates/Temp/searchresults.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>TheTalkSquare</title>

    <meta name="generator" content="Bootply" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <style>
        .jumbotron {padding: 5px;}
    </style>
    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/stylish-portfolio.css' %}" rel="stylesheet">
    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "70%";
            // document.getElementById("flipkart-navbar").style.width = "50%";
            document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.body.style.backgroundColor = "rgba(0,0,0,0)";
        }
    </script>
</head>
<body  style="background: #eeeeee">

<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<div id="flipkart-navbar" style="background: #576396">
    <div class="container">
        <div class="row row1" style="margin-top: 20px;padding-bottom:20px">
            <div class="col-sm-2">
                <h2 style="margin:0px;"><span class="smallnav menu" onclick="openNav()">☰ OPINIUM</span></h2>
                <h1 style="margin:0px;"><span class="largenav">OPINIUM</span></h1>
            </div>
            <div class="flipkart-navbar-search smallsearch col-sm-8">
                <div class="row">

                    <form class="form" method="POST" action="{% url 'main:search' %}"><!--Not applied yet -->
                        {% csrf_token %}
                        <input style="color:#000" class="flipkart-navbar-input col-xs-11" name="topic_text" type=""
                               placeholder="Search for Issues and more" required>
                        <button class="flipkart-navbar-button col-xs-1">
                            <svg width="15px" height="15px">
                                <path d="M11.618 9.897l4.224 4.212c.092.09.1.23.02.312l-1.464 1.46c-.08.08-.222.072-.314-.02L9.868 11.66M6.486 10.9c-2.42 0-4.38-1.955-4.38-4.367 0-2.413 1.96-4.37 4.38-4.37s4.38 1.957 4.38 4.37c0 2.412-1.96 4.368-4.38 4.368m0-10.834C2.904.066 0 2.96 0 6.533 0 10.105 2.904 13 6.486 13s6.487-2.895 6.487-6.467c0-3.572-2.905-6.467-6.487-6.467 "></path>
                            </svg>
                        </button>
                    </form>
                </div>
            </div>
            <div class="col-sm-1">
                <ul style="padding-top:5px;list-style:none">
                    {% if user_id %}
                    <li><h4 style="font-size: 15px;font-weight: bolder"> {{ user_id.user_name }}</h4> </li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-sm-1">
                <ul style="padding-top:5px;list-style:none">
                    {% if user_id %}
                    <li><a style="font-size: 15px;font-weight: bolder" href="{% url 'login:logout' %}" class="btn btn-warning">Log Out</a></li>
                    {% else %}
                    <li><a style="font-size: 15px;font-weight: bolder" href="{% url 'login:login' %}" class="btn btn-warning">Log In</a></li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </div>
</div>

   <div class="container-fluid" style="margin-top: 20px">
    <div class="row">

        <div class="col-sm-9" style="margin-top: 20px">
            <ul style="list-style-type: none">
                {% if list %}
                    {% for i in list %}
                        <div style="border:1px solid #eeeeee;background:#fff;margin-bottom: 5px;border-radius:5px;padding:0px 20px 10px 20px">
                            <h3><a
                                    href="{% url 'main:topic' i.id %}">{{ i.topic_text }}</a>
                            </h3>

                            <p class="lead" style="font-size:15px"> >&nbsp;{{ i.user.user_name }}
                            </p>
                            {% if i.tag_set.all %}
                                Tags:
                                {% for j in i.tag_set.all %}
                                    <a href=""><span
                                            class="badge badge-info">
                                {{ j.tag_name }}
        </span></a>
                                {% endfor %}
                            {% else %}

                            {% endif %}

                        </div>
                    {% endfor %}
                {% else %}
                    <li>No topics available</li>
                {% endif %}
            </ul>
        </div>
<script type="text/javascript"
        src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5892d5e98848c5c0"></script>
</body>
</html>