TheTalkSquare/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^user', include('login.urls')),
    url(r'^admin/', admin.site.urls),
]

login/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

app_name = 'login' 
#This sets application namespace to diffretiate urls of different apps.

urlpatterns = [
    #url for login-page:
    url(r'/login$', views.login, name='login'),

    #url for signup-page:
    url(r'/signup$', views.signup, name='signup'),

    #url to log in a user:
    url(r'/log_req$', views.logInReq, name='login_req'),
    
    #url for create-user:
    url(r'/register_user$', views.register, name='register_user'),

    #url for logout:
    url(r'/logout$', views.logout, name='logout'),
]

main/urls.py
from django.conf.urls import url

from . import views


app_name = 'main' 
#This sets application namespace to diffretiate urls of different apps.

urlpatterns = [
    #url for home-page:
    url(r'^$', views.index, name='index'),

    #url to Enter a new Topic:
    url(r'^add_topic$', views.addtopic, name='addtopic'),

    #url to Enter a new Topic:
    url(r'^add_opinion$', views.addopinion, name='addopinion'),

    #url to topic page:
    url(r'^(?P<pk>[0-9]+)/topic$', views.TopicView.as_view(), name='topic'),

    #url to search a topic:
    url(r'^search$', views.search, name='search'),
]

login/models.py
from django.db import models

class User(models.Model):
    user_name = models.CharField(max_length=80,unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=120)
    pwd= models.CharField(max_length=80)
    #no_of_topics=models.IntegerField(default=0)
    #type_user=models.BooleanField()
    def __str__(self):
        return self.user_name

login/forms.py
from django import forms

class SignupForm(forms.Form):
    username=forms.CharField(max_length = 80)
    firstname = forms.CharField(max_length=30)
    lastname = forms.CharField(max_length=30)
    email = forms.CharField(max_length=120)
    pwd= forms.CharField(max_length=80)

class LoginForm(forms.Form):
    username=forms.CharField(max_length = 80)
    pwd= forms.CharField(max_length=80)

login/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect

from django.urls import reverse
#for older versoins of Django use:
#from django.core.urlresolvers import reverse

from .models import User
from .forms import SignupForm,LoginForm

def login(request):
    return render(request, 'Html/login.html')
def signup(request):
    return render(request, 'Html/signup.html')

def register(request):
    if request.method == 'POST':
        signup=SignupForm(request.POST)
        if signup.is_valid():
            p=User(user_name=signup.cleaned_data.get('username'),first_name=signup.cleaned_data.get('firstname'),last_name=signup.cleaned_data.get('lastname'),email=signup.cleaned_data.get('email'),pwd=signup.cleaned_data.get('pwd'))
            p.save()
    request.session['user_id'] = p.id
    return HttpResponseRedirect(reverse('main:index'))

def logInReq(request):
    if request.method == 'POST':
        log=LoginForm(request.POST)
        if log.is_valid():
            try:
                user=User.objects.get(user_name=log.cleaned_data.get('username'),pwd=log.cleaned_data.get('pwd'))
                request.session['user_id'] = user.id
                return HttpResponseRedirect(reverse('main:index'))
            except User.DoesNotExist:
                return HttpResponse("WRONG USERNAME OR PASSWORD")

def logout(request):
   try:
      del request.session['user_id']
   except:
      pass
   return HttpResponseRedirect(reverse('main:index'))

login/templates/Html/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>TheTalkSquare</title>
		<meta name="generator" content="Bootply" />
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="{% static 'css/styles.css' %}" rel="stylesheet">
		
		 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/stylish-portfolio.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic' %}" rel="stylesheet" type="text/css">
	
	</head>
	<body>
<!--login modal-->
<header id="top" class="header">
        <div class="text-vertical-center">
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <h1 class="text-center">Login</h1>
      </div>


      <div class="modal-body">
          <form class="form col-md-12 center-block" method="POST" action="{% url 'login:login_req' %}">
			{% csrf_token %} 
            <div class="form-group">
              <input type="text" class="form-control input-lg" name="username" placeholder="UserName" required>
            </div>
            <div class="form-group">
              <input type="password" class="form-control input-lg" name="pwd" placeholder="Password" required>
            </div>
            <div class="form-group">
              <button class="btn btn-primary btn-lg btn-block">Sign In</button>
              <!--<span class="pull-right"><a href="signup.html">Register</a></span>
			  <span><a href="#">Need help?</a></span>-->
            </div>
          </form>
      </div>


      <div class="modal-footer">
      </div>
  </div>
  </div>
</div>
	
</div>
</header>
</body>
</html>

login/templates/Html/signup.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>TheTalkSquare</title>
		<meta name="generator" content="Bootply" />
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="{% static 'css/styles.css' %}" rel="stylesheet">
		
		 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/stylish-portfolio.css' %}" rel="stylesheet">

    </head>
	<body>
<!--login modal-->
<header id="top" class="header">
        <div class="text-vertical-center">
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <h1 class="text-center">Sign-Up</h1>
      </div>
      <div class="modal-body">
          <form class="form col-md-12 center-block" method="POST" action="{% url 'login:register_user' %}">
			{% csrf_token %} 
	    <div class="form-group">
              <input type="text" class="form-control input-lg" name="username" placeholder="User-Name" required>
            </div>
			<div class="form-group">
              <input type="text" class="form-control input-lg" name="firstname" placeholder="First-Name" required>
			</div>
			<div class="form-group">
			  <input type="text" class="form-control input-lg" name="lastname" placeholder="Last-Name" required>
            </div>
            <div class="form-group">
              <input type="email" class="form-control input-lg" name="email" placeholder="Email-ID" required>
            </div>
            <div class="form-group">
              <input type="password" class="form-control input-lg" name="pwd" placeholder="Password" required>
            </div>
 			<div class="form-group">
              <input type="password" class="form-control input-lg" name="cpwd" placeholder="Confirm-Password" required>
            </div>
            <div class="form-group">
              <button class="btn btn-primary btn-lg btn-block">Sign Up</button>
              
            </div>
          </form>
      </div>
      <div class="modal-footer">
          	
      </div>
  </div>
  </div>
</div>
</div>
</header>
	</body>
</html>